/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a typical app. It is checked in here so
// the thin test UI can typecheck before the first `next dev` run.
